server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;

    gzip on;
    gzip_types text/html text/css application/javascript image/svg+xml;

    location / {
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
